name: Continuous Integration

on: [ push, pull_request ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5

      - name: setup python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: install dependencies
        run: make deps

      - name: run tests
        run: make test
      
      - name: run linter
        run: make lint
